### ISSUE TITLE
Right-click menu breaks

### ISSUE THREAD

**Issue by AlexanderPico** [nrnb/gsoc2012ritisha#1]
Right-click menu breaks. Steps to reproduce:

1. Open any network
2. Right-click on canvas > Add node
3. Right-click on canvas!

Exp: menu
Obs: No menu and stack trace (below)

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.nrnb.pathexplorer.tasks.IncludeNetworkViewTaskFactory.isReady(IncludeNetworkViewTaskFactory.java:35)
	at org.cytoscape.ding.impl.StaticTaskFactoryProvisioner$1.isReady(StaticTaskFactoryProvisioner.java:52)
	at org.cytoscape.ding.impl.PopupMenuHelper.createMenuItem(PopupMenuHelper.java:506)
	at org.cytoscape.ding.impl.PopupMenuHelper.addMenuItem(PopupMenuHelper.java:421)
	at org.cytoscape.ding.impl.PopupMenuHelper.createNetworkViewMenu(PopupMenuHelper.java:272)
	at org.cytoscape.ding.impl.InputHandlerGlassPane$ContextMenuListener.showContextMenu(InputHandlerGlassPane.java:555)
	at org.cytoscape.ding.impl.InputHandlerGlassPane$ContextMenuListener.mousePressed(InputHandlerGlassPane.java:531)
	at org.cytoscape.ding.internal.util.OrderedMouseAdapter.fire(OrderedMouseAdapter.java:83)
	at org.cytoscape.ding.internal.util.OrderedMouseAdapter.mousePressed(OrderedMouseAdapter.java:60)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6629)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at org.cytoscape.ding.impl.InputHandlerGlassPane.processMouseEvent(InputHandlerGlassPane.java:238)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by AlexanderPico** [comment]
Here is NPE line: https://github.com/nrnb/gsoc2012ritisha/blob/master/src/org/nrnb/pathexplorer/tasks/IncludeNetworkViewTaskFactory.java#L35

**Comment by AlexanderPico** [comment]
NPE can be resolved by entering a boolean value into `isExcludedFromPaths` column for the newly added node.
